import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
import webpush from 'npm:web-push@3.6.7';

// Internal helper — invoked by other backend functions (createPublicLead,
// sendAppointmentReminders) to deliver a web push notification to every
// active PushSubscription record owned by a given user.
// It runs with the service role (no user auth) so public-endpoint callers
// and scheduled automations can use it.
// VAPID keys are loaded from the VapidKeyPair entity (auto-generated by
// getVapidPublicKey) — no secrets required.

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json();
    const { user_id, title, body: messageBody, url, _internalToken } = body;

    // ── Auth: this is an internal helper invoked only by other backend
    //    functions (createPublicLead, sendAppointmentReminders) via the
    //    service role. External/unauthenticated HTTP requests must NOT be
    //    able to dispatch arbitrary push notifications to users, so we gate
    //    on a backend-only bearer token (VAPID_PRIVATE_KEY) that only
    //    server-side callers can read from the environment. Fail-closed.
    const INTERNAL_TOKEN = Deno.env.get('VAPID_PRIVATE_KEY');
    if (!INTERNAL_TOKEN || _internalToken !== INTERNAL_TOKEN) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user_id || !title) {
      return Response.json({ error: 'user_id and title are required' }, { status: 400 });
    }

    // Load VAPID key pair from DB (generated and stored by getVapidPublicKey)
    const keyPairs = await base44.asServiceRole.entities.VapidKeyPair.list();
    let keyPair;
    if (keyPairs.length === 0) {
      const generated = webpush.generateVAPIDKeys();
      keyPair = await base44.asServiceRole.entities.VapidKeyPair.create({
        public_key: generated.publicKey,
        private_key: generated.privateKey,
        label: 'default',
      });
    } else {
      keyPair = keyPairs[0];
    }

    let vapidEmail = (Deno.env.get('VAPID_EMAIL') || '').replace(/^"+|"+$/g, '').trim();
    if (!vapidEmail) vapidEmail = 'mailto:support@bingooconnect.com';
    if (!vapidEmail.startsWith('mailto:')) vapidEmail = 'mailto:' + vapidEmail;

    webpush.setVapidDetails(vapidEmail, keyPair.public_key, keyPair.private_key);

    const subscriptions = await base44.asServiceRole.entities.PushSubscription.filter({
      user_id,
      enabled: true,
    });

    if (subscriptions.length === 0) {
      return Response.json({ success: true, sent: 0, message: 'No active subscriptions' });
    }

    const payload = JSON.stringify({
      title,
      body: messageBody || '',
      url: url || '/bingoo',
    });

    let sent = 0;
    let failed = 0;
    const staleIds: string[] = [];

    for (const sub of subscriptions) {
      try {
        await webpush.sendNotification(
          {
            endpoint: sub.endpoint,
            keys: { p256dh: sub.p256dh, auth: sub.auth },
          },
          payload
        );
        sent++;
        try {
          await base44.asServiceRole.entities.PushSubscription.update(sub.id, {
            last_used_at: new Date().toISOString(),
          });
        } catch (e) {
          /* non-blocking */
        }
      } catch (err: any) {
        failed++;
        console.error(`Push failed for sub ${sub.id}:`, err.statusCode, err.message);
        // 410 Gone / 404 = subscription expired — clean it up
        if (err.statusCode === 410 || err.statusCode === 404) {
          staleIds.push(sub.id);
        }
      }
    }

    for (const id of staleIds) {
      try {
        await base44.asServiceRole.entities.PushSubscription.delete(id);
      } catch (e) {
        /* non-blocking */
      }
    }

    return Response.json({ success: true, sent, failed, cleaned: staleIds.length });
  } catch (error) {
    console.error('sendPushNotification error:', error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
});