export const PRODUCTS = [
  {
    id: 'nfc-card',
    name: 'NFC Business Card',
    description: 'Premium PVC NFC card — tap to share your digital profile instantly.',
    price: 14.99,
    emoji: '💳',
    category: 'card',
    badge: 'Best Seller',
    features: [
      'Premium PVC material',
      'Pre-programmed with your profile URL',
      'Works with all NFC-enabled phones',
      'Waterproof & scratch-resistant',
    ],
  },
  {
    id: 'nfc-keychain',
    name: 'NFC Keychain',
    description: 'Durable keychain tag — always with you, always ready to share.',
    price: 12.99,
    emoji: '🔑',
    category: 'accessory',
    badge: null,
    features: [
      'Durable ABS plastic',
      'Compact & lightweight',
      'Works with all NFC-enabled phones',
      'Multiple color options',
    ],
  },
  {
    id: 'nfc-sticker',
    name: 'NFC Sticker',
    description: 'Versatile NFC sticker — stick it anywhere for instant sharing.',
    price: 9.99,
    emoji: '🏷️',
    category: 'accessory',
    badge: null,
    features: [
      'Strong adhesive backing',
      'Ultra-thin design',
      'Works on most surfaces',
      'Pack of 2',
    ],
  },
  {
    id: 'nfc-stand',
    name: 'NFC Desk Stand',
    description: 'Elegant desk stand for your workspace — let clients tap to connect.',
    price: 24.99,
    emoji: '🖥️',
    category: 'stand',
    badge: 'New',
    features: [
      'Aluminum & acrylic build',
      'Stable weighted base',
      'NFC chip embedded',
      'Perfect for reception desks',
    ],
  },
  {
    id: 'nfc-bundle',
    name: 'Starter Bundle',
    description: '1 Card + 1 Keychain + 1 Sticker — everything you need to get started.',
    price: 29.99,
    emoji: '📦',
    category: 'bundle',
    badge: 'Save $8',
    features: [
      '1× NFC Business Card',
      '1× NFC Keychain',
      '1× NFC Sticker',
      'Free priority shipping',
    ],
  },
  {
    id: 'nfc-bulk-10',
    name: '10-Pack Cards',
    description: 'Bulk NFC cards for your team — great for corporate rollouts.',
    price: 99.99,
    emoji: '🗂️',
    category: 'bulk',
    badge: 'Corporate',
    features: [
      '10× Premium NFC Cards',
      'Custom branding available',
      'Bulk discount applied',
      'Free shipping',
    ],
  },
];