// VIP product uses nfc-bundle ID since no separate VIP ID is backend-supported yet.
// Future: add nfc-vip-card to backend price map when ready.
export const PRODUCTS = [
  {
    id: 'nfc-card',
    name: 'NFC Business Card',
    tagline: 'Tap to share your digital profile instantly.',
    description: 'Premium matte PVC NFC card pre-programmed with your Bingoo profile. Works with all NFC-enabled smartphones — no app required.',
    price: 19.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/dc503cd64_generated_image.png',
    category: 'card',
    badge: 'Best Seller',
    features: [
      'Premium matte PVC finish',
      'Pre-programmed with your profile URL',
      'Compatible with all NFC phones',
      'Waterproof & scratch-resistant',
    ],
  },
  {
    id: 'nfc-keychain',
    name: 'NFC Keychain',
    tagline: 'Always on you. Always ready to share.',
    description: 'Compact NFC keychain tag that attaches to any key ring. Tap to share your full Bingoo profile in seconds.',
    price: 14.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/b9379d834_generated_image.png',
    category: 'keychain',
    badge: null,
    features: [
      'Durable ABS casing',
      'Compact & lightweight',
      'Fits any standard key ring',
      'Works with all NFC phones',
    ],
  },
  {
    id: 'nfc-sticker',
    name: 'NFC Sticker',
    tagline: 'Stick it anywhere. Share everywhere.',
    description: 'Ultra-thin NFC stickers with strong adhesive backing. Perfect for laptops, windows, packaging, or any flat surface.',
    price: 7.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/c5cc31522_generated_image.png',
    category: 'sticker',
    badge: null,
    features: [
      'Strong adhesive backing',
      'Ultra-thin design',
      'Works on most flat surfaces',
      'Pack of 2',
    ],
  },
  {
    id: 'nfc-stand',
    name: 'NFC Desk Stand',
    tagline: 'Let clients tap and connect at your counter.',
    description: 'Sleek acrylic desk stand for salons, offices, restaurants, and reception counters. NFC chip embedded — tap to connect.',
    price: 34.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/13f7e892a_generated_image.png',
    category: 'stand',
    badge: 'New',
    features: [
      'Acrylic & aluminum build',
      'Stable weighted base',
      'Embedded NFC chip',
      'Ideal for countertops & desks',
    ],
  },
  {
    id: 'nfc-bracelet',
    name: 'NFC Bracelet',
    tagline: 'Wear your profile. Share with a tap.',
    description: 'Comfortable silicone NFC wristband with an embedded chip. Share your Bingoo profile directly from your wrist.',
    price: 24.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/cbccc08cd_generated_image.png',
    category: 'bracelet',
    badge: 'New',
    features: [
      'Soft silicone wristband',
      'Water-resistant design',
      'Works with all NFC phones',
      'Adjustable sizing',
    ],
  },
  {
    id: 'nfc-bundle',
    name: 'Starter Bundle',
    tagline: 'Card + Keychain + Stickers. Everything you need.',
    description: 'The complete Bingoo NFC starter kit. One card, one keychain, two stickers — everything to share your profile everywhere.',
    price: 29.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/add0b8f00_generated_image.png',
    category: 'bundle',
    badge: 'Save $13',
    features: [
      '1× NFC Business Card',
      '1× NFC Keychain',
      '2× NFC Stickers',
      'Free priority shipping',
    ],
  },
  {
    id: 'nfc-bulk-10',
    name: '10-Pack Corporate Cards',
    tagline: 'Equip your entire team in one order.',
    description: 'Bulk NFC business cards for teams and corporate rollouts. Ideal for events, staff onboarding, and enterprise deployment.',
    price: 99.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/c64d43b4a_generated_image.png',
    category: 'bulk',
    badge: 'Corporate',
    features: [
      '10× Premium NFC Cards',
      'Custom branding available',
      'Bulk discount applied',
      'Free express shipping',
    ],
  },
  // VIP product uses nfc-bundle checkout ID until a dedicated nfc-vip-card backend price is added.
  // To unlock as a separate SKU: add 'nfc-vip-card' to the backend price map in createShopCheckout.js.
  {
    id: 'nfc-bundle',  // mapped to bundle checkout until vip ID is supported
    name: 'VIP Black Card',
    tagline: 'Ultra-premium black card with gold finish.',
    description: 'Exclusive matte-black NFC card with gold foil Bingoo branding. The premium card for executives, founders, and VIP clients.',
    price: 29.99,
    image: 'https://media.base44.com/images/public/692bd9007b93ba81de543346/5308234db_generated_image.png',
    category: 'vip',
    badge: 'VIP',
    features: [
      'Matte-black premium finish',
      'Gold foil Bingoo branding',
      'Same NFC functionality',
      'Limited edition — exclusive feel',
    ],
  },
];