import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Bell, Check, ChevronDown, CreditCard, Grid2X2, KeyRound, List, Package, PackageSearch, ShieldCheck, ShoppingCart, Store, Tag, Truck, Watch } from 'lucide-react';
import { PRODUCTS, COLLECTIONS, isPurchasable } from '@/lib/shopProducts';
import { addToCart, getCartCount } from '@/lib/cartStore';
import { InfinityMark } from '@/components/bingoo/ui/BingooBrand';
import FactoryProductMedia from '@/components/shop/FactoryProductMedia';

const NAVY='#0b2149', NAVY_DEEP='#071A3D', ORANGE='#f97316';
const CATEGORIES=[
{id:'all',label:'All Devices',icon:CreditCard,test:()=>true},
{id:'profile',label:'Profile Devices',icon:CreditCard,test:p=>p.flow!=='asset_protection'&&p.category!=='stand'&&!p.id?.includes('bundle')},
{id:'wearables',label:'Wearables',icon:Watch,test:p=>p.category==='bracelet'||p.category==='badge'},
{id:'desk',label:'Desk & Counter',icon:Store,test:p=>p.category==='stand'||p.collection==='business'},
{id:'keys',label:'Key Accessories',icon:KeyRound,test:p=>p.category==='keychain'},
{id:'tags',label:'Smart Tags',icon:Tag,test:p=>p.category==='tag'},
{id:'bundles',label:'Bundles',icon:Package,test:p=>p.id?.includes('bundle')||p.id?.includes('pack')}];
const TRUST=[{icon:ShieldCheck,title:'Secure Checkout',copy:'Stripe encrypted'},{icon:Truck,title:'Shipping',copy:'Calculated at checkout'},{icon:Package,title:'Bingoo Hardware',copy:'Factory-ready catalog'}];
function Toggle({on,value}){return <button onClick={on} className="w-10 h-6 rounded-full p-1" style={{background:value?ORANGE:'#e2e8f0'}}><span className="block w-4 h-4 bg-white rounded-full transition-transform" style={{transform:value?'translateX(16px)':'none'}}/></button>}
function ProductCard({p,added,onAdd,list}){const buy=isPurchasable(p),collection=COLLECTIONS.find(c=>c.id===p.collection);return <motion.article layout whileHover={{y:list?0:-3}} className={`${list?'grid md:grid-cols-[250px_1fr]':'flex flex-col'} bg-white rounded-2xl border border-slate-200 overflow-hidden`} style={{boxShadow:'0 7px 24px rgba(11,33,73,.05)'}}><Link to={`/product/${p.id}`}><div className={`${list?'h-[210px]':'h-[230px]'} relative bg-white`}><FactoryProductMedia product={p} className="w-full h-full"/>{p.badge&&<span className="absolute top-4 left-4 text-[9px] uppercase font-black text-white rounded-full px-3 py-1" style={{background:p.availability==='coming_soon'?'#64748b':ORANGE}}>{p.badge}</span>}</div></Link><div className="p-5 flex flex-col flex-1 border-t border-slate-100"><p className="text-[10px] uppercase tracking-wider font-black mb-1" style={{color:ORANGE}}>{p.flow==='asset_protection'?'Asset Device':'Profile Device'} · {p.bestFor||collection?.label}</p><Link to={`/product/${p.id}`}><h3 className="font-black text-lg" style={{color:NAVY}}>{p.name}</h3></Link><p className="text-[13px] text-slate-500 leading-relaxed mt-1 mb-4 line-clamp-2">{p.tagline}</p><div className="mt-auto flex items-end justify-between gap-2">{buy?<><b className="text-[23px] text-slate-900">${p.price.toFixed(2)}</b><div className="flex gap-2"><Link to={`/product/${p.id}`} className="px-4 py-2.5 rounded-xl border border-slate-200 text-xs font-black text-slate-700">View</Link><button onClick={()=>onAdd(p)} className="px-4 py-2.5 rounded-xl text-xs font-black text-white flex gap-1.5 items-center" style={{background:added?'#16a34a':ORANGE}}>{added?<><Check className="w-3.5"/>Added</>:<><ShoppingCart className="w-3.5"/>Add to Cart</>}</button></div></>:<><b className="text-sm text-slate-400">Coming Soon</b><Link to={`/product/${p.id}`} className="px-4 py-2.5 rounded-xl text-xs font-black text-white flex gap-1 items-center" style={{background:NAVY}}><Bell className="w-3.5"/>Notify Me</Link></>}</div></div></motion.article>}

export default function Shop(){
const [cart,setCart]=useState(getCartCount()),[added,setAdded]=useState(null),[category,setCategory]=useState('all'),[best,setBest]=useState(false),[fresh,setFresh]=useState(false),[stock,setStock]=useState(true),[sort,setSort]=useState('featured'),[view,setView]=useState('grid'),[price,setPrice]=useState(100);
useEffect(()=>setCart(getCartCount()),[]);
const counts=useMemo(()=>Object.fromEntries(CATEGORIES.map(c=>[c.id,PRODUCTS.filter(c.test).length])),[]);
const items=useMemo(()=>{const f=CATEGORIES.find(c=>c.id===category)||CATEGORIES[0];let x=PRODUCTS.filter(p=>f.test(p)&&(!stock||isPurchasable(p))&&(!best||String(p.badge||'').toLowerCase().includes('best'))&&(!fresh||(String(p.badge||'').toLowerCase().includes('new')||p.availability==='coming_soon'))&&(!isPurchasable(p)||p.price<=price));if(sort==='low')x=[...x].sort((a,b)=>(a.price??999)-(b.price??999));if(sort==='high')x=[...x].sort((a,b)=>(b.price??-1)-(a.price??-1));if(sort==='name')x=[...x].sort((a,b)=>a.name.localeCompare(b.name));return x},[category,best,fresh,stock,sort,price]);
const add=p=>{if(!isPurchasable(p))return;addToCart(p,1);setCart(getCartCount());setAdded(p.id);setTimeout(()=>setAdded(null),1400)};
return <div className="min-h-screen" style={{background:'#f7f8fb'}}>
<header className="sticky top-0 z-30" style={{background:NAVY_DEEP}}><div className="max-w-[1500px] mx-auto px-5 h-[76px] flex items-center justify-between"><Link to="/" className="flex items-center gap-3"><InfinityMark size={42} color={ORANGE} strokeWidth={3.4} glow/><b className="text-white text-lg hidden sm:block">BINGOO CONNECT</b></Link><nav className="hidden md:flex items-center gap-9 text-sm font-bold text-white/75 h-full"><Link to="/#features">Features</Link><Link to="/">Industries</Link><Link to="/#pricing">Pricing</Link><Link to="/shop" className="relative text-white h-full flex items-center">Shop<span className="absolute bottom-0 inset-x-0 h-[3px]" style={{background:ORANGE}}/></Link></nav><Link to="/cart" className="relative text-white p-3"><ShoppingCart className="w-5"/>{cart>0&&<span className="absolute top-0 right-0 w-5 h-5 rounded-full text-[10px] font-black flex items-center justify-center" style={{background:ORANGE}}>{cart}</span>}</Link></div></header>
<main className="max-w-[1500px] mx-auto px-5 py-9"><section className="grid lg:grid-cols-[1fr_auto] gap-7 items-end mb-8"><div><p className="text-xs font-black uppercase tracking-[.18em] mb-3" style={{color:ORANGE}}>Bingoo NFC Hardware</p><h1 className="text-4xl md:text-5xl font-black mb-3" style={{color:NAVY}}>Shop real NFC devices.</h1><p className="text-slate-500 text-lg max-w-2xl">A production-focused hardware catalog for professional identity, teams and asset recovery. The same SKU follows you from this shelf to product page, cart and checkout.</p></div><div className="grid sm:grid-cols-3 gap-3">{TRUST.map(t=>{const I=t.icon;return <div key={t.title} className="bg-white border border-slate-200 rounded-2xl px-5 py-4 flex items-center gap-3 min-w-[205px]"><I className="w-8 h-8" style={{color:NAVY}}/><div><b className="text-xs block" style={{color:NAVY}}>{t.title}</b><span className="text-xs text-slate-500">{t.copy}</span></div></div>})}</div></section>
<section className="grid lg:grid-cols-[280px_1fr] gap-6 items-start"><aside className="space-y-4 lg:sticky lg:top-[94px]"><div className="bg-white rounded-2xl border border-slate-200 p-4"><p className="text-xs font-black uppercase tracking-wider text-slate-400 px-2 mb-3">Device Categories</p>{CATEGORIES.map(c=>{const I=c.icon,a=category===c.id;return <button key={c.id} onClick={()=>setCategory(c.id)} className="w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm font-bold" style={{background:a?'#fff3eb':'transparent',color:NAVY}}><I className="w-4" style={{color:a?ORANGE:'#64748b'}}/><span className="flex-1 text-left">{c.label}</span><span className="text-xs text-slate-400">{counts[c.id]}</span></button>})}</div><div className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div className="p-4 border-b"><p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-4">Filters</p><div className="space-y-4"><div className="flex justify-between text-sm font-semibold"><span>Best Sellers</span><Toggle value={best} on={()=>setBest(!best)}/></div><div className="flex justify-between text-sm font-semibold"><span>New / Coming</span><Toggle value={fresh} on={()=>setFresh(!fresh)}/></div><div className="flex justify-between text-sm font-semibold"><span>In Stock Only</span><Toggle value={stock} on={()=>setStock(!stock)}/></div></div></div><div className="p-4"><p className="text-xs font-black uppercase tracking-wider text-slate-400 mb-4">Price Range</p><div className="flex justify-between text-xs font-black mb-3"><span>$0</span><span>${price}+</span></div><input type="range" min="10" max="100" value={price} onChange={e=>setPrice(+e.target.value)} className="w-full accent-orange-500"/></div></div></aside>
<div><div className="bg-white rounded-2xl border border-slate-200 p-4 mb-5 flex items-center justify-between gap-4"><span className="text-sm text-slate-500"><b style={{color:NAVY}}>{items.length}</b> devices</span><div className="flex gap-3"><div className="relative"><select value={sort} onChange={e=>setSort(e.target.value)} className="appearance-none border border-slate-200 rounded-xl pl-4 pr-10 py-2.5 text-sm font-semibold bg-white"><option value="featured">Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option><option value="name">Name: A–Z</option></select><ChevronDown className="absolute right-3 top-3 w-4 text-slate-400 pointer-events-none"/></div><div className="flex border border-slate-200 rounded-xl overflow-hidden"><button onClick={()=>setView('grid')} className="w-11 flex justify-center items-center" style={{color:view==='grid'?ORANGE:'#64748b'}}><Grid2X2 className="w-4"/></button><button onClick={()=>setView('list')} className="w-11 flex justify-center items-center border-l" style={{color:view==='list'?ORANGE:'#64748b'}}><List className="w-4"/></button></div></div></div><motion.div layout className={view==='grid'?'grid sm:grid-cols-2 xl:grid-cols-3 gap-4':'grid gap-4'}>{items.map(p=><ProductCard key={p.id} p={p} added={added===p.id} onAdd={add} list={view==='list'}/>)}</motion.div>{!items.length&&<div className="bg-white border border-dashed rounded-3xl p-12 text-center mt-4"><PackageSearch className="mx-auto text-slate-300 mb-3"/><b style={{color:NAVY}}>No devices match these filters.</b></div>}</div></section></main></div>}
